Repository Bedrock-im/bedrock, pull requests merged in 2025-07, with the labels that each got.

#108 fix: sonner
  front/src/app/globals.css
Labels: bug

#111 fix(login): External providers login
  front/src/layouts/watchers.tsx
  front/src/services/aleph.ts
  front/src/stores/account.ts
Labels: enhancement

#114 feat(back): Working topup credits
  back/main.py
  back/poetry.lock
  back/pyproject.toml
  back/thirdweb_webhook.py
  front/src/apis/usernames/sdk.gen.ts
  front/src/apis/usernames/types.gen.ts
  front/src/components/CreditTopUp.tsx
Labels: enhancement

#113 Update introduction.md
  README.md
  docs/index.md
  docs/introduction.md
Labels: documentation
